### ISSUE TITLE
후기 작성하기 레이아웃 제작

### ISSUE THREAD

**Issue by snacknam** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#107]
## 📌 Issue
후기 작성하기 뷰의 레이아웃 작성

## 📝 To-do

- [x] 종료 투표 뷰
- [x] 구매여부 선택
- [x] 후기 내용

**Comment by anonyapple** [comment]
ㅋㅋ루삥뽕삥빵뽕
