### ISSUE TITLE
소비 성향 테스트 레이아웃 제작

### ISSUE THREAD

**Issue by minnnidev** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#111]
## 📌 Issue

소비 성향 테스트 레이아웃

## 📝 To-do

- [x] 테스트지 
- [x] 결과 로직
- [x] 결과 페이지 더미 레이아웃만 잡아놓기
- [x] 동률일 때 고민
- [x] 화면 전환 구현

**Comment by anonyapple** [comment]
ㅋㅋ루삥뽕삥빵뽕
