### ISSUE TITLE
상세뷰 UI만들기

### ISSUE THREAD

**Issue by sunhofficial** [DeveloperAcademy-POSTECH/MacC-Team8-2HoSun#92]
## 📌 Issue
바뀐 상세뷰의 UI를 구현!
## 📝 To-do

- [x] 댓글창
- [x] 상세셀
- [x] 차트
- [ ] 디자인 수정된 작업하기

**Comment by anonyapple** [comment]
ㅋㅋ루삥뽕삥빵뽕
